# Generated by Django 3.2 on 2023-12-24 03:41

from django.db import migrations, models
import django.db.models.deletion
import myapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True, validators=[myapp.validators.validate_first_letter], verbose_name='Name')),
                ('age', models.PositiveSmallIntegerField(blank=True, validators=[myapp.validators.validate_value], verbose_name='Age')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, validators=[myapp.validators.validate_first_letter], verbose_name='Title')),
                ('content', models.TextField(blank=True, max_length=2000, verbose_name='Content')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notes', to='myapp.person')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['id'],
            },
        ),
    ]
