# Generated by Django 3.2 on 2024-01-14 00:40

from django.db import migrations, models
import myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[myapp.validators.validate_value], verbose_name='Age'),
        ),
    ]
